application: szsy2015countdown
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: index.application

libraries:
- name: webapp2
  version: 2.5.2
