application: szsy2015countdown
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico
- url: /.*
  script: index.application

libraries:
- name: webapp2
  version: 2.5.2
- name: webob
  version: 1.2.3
- name: jinja2
  version: 2.6
